/******************************************************************************
* File Name:   main.c
*
* Description: This is the source code for the XMC MCU: TSE Calc Temperature Example
*              for ModusToolbox. This code example calculates temperature readings
*              from the on chip temperature sensor and sends over UART periodically
*              every 1s. 
*
* Related Document: See README.md
*
******************************************************************************
*
* Copyright (c) 2015-2021, Infineon Technologies AG
* All rights reserved.                        
*                                             
* Boost Software License - Version 1.0 - August 17th, 2003
* 
* Permission is hereby granted, free of charge, to any person or organization
* obtaining a copy of the software and accompanying documentation covered by
* this license (the "Software") to use, reproduce, display, distribute,
* execute, and transmit the Software, and to prepare derivative works of the
* Software, and to permit third-parties to whom the Software is furnished to
* do so, all subject to the following:
* 
* The copyright notices in the Software and this entire statement, including
* the above license grant, this restriction and the following disclaimer,
* must be included in all copies of the Software, in whole or in part, and
* all derivative works of the Software, unless such copies or derivative
* works are solely in the form of machine-executable object code generated by
* a source language processor.
* 
* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
* IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
* FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
* SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
* FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
* ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
* DEALINGS IN THE SOFTWARE.
*                                                                              
*****************************************************************************/
#include <stdio.h>
#include <string.h>
#include "cybsp.h"
#include "cy_utils.h"
#include "xmc_scu.h"
#include "xmc_gpio.h"
#include "xmc_uart.h"

/*******************************************************************************
* Defines
*******************************************************************************/

/* Declarations for LED toggle and UART transmission timing */
#define TICKS_PER_SECOND 1000

/* Declaration of array to store the message to be transmitted */
uint8_t data[50];

/*******************************************************************************
* Function Name: SysTick_Handler
********************************************************************************
* Summary:
* Function called by system timer every millisecond.
*
* Parameters:
*  void
*
* Return:
*  void
*
*******************************************************************************/

void SysTick_Handler(void)
{
    static uint32_t ticks = 0U;
    uint32_t temp_C = 0;
    uint32_t temp_k = 0;
    uint32_t index;
    ++ticks;

    if (ticks == TICKS_PER_SECOND)
    {
        ticks = 0U;

        /* Toggle the LED */
        XMC_GPIO_ToggleOutput(CYBSP_USER_LED_PORT, CYBSP_USER_LED_PIN);

        /* Calculate temperature of the chip in Kelvin */
        temp_k = XMC_SCU_CalcTemperature();

        /* Convert temperature to Celsius */
        temp_C = temp_k - 273;

        sprintf((char *)data, "\r\nChip temperature: %lu\r\n",temp_C);
        uint8_t n = strlen((char *)data);

        for (index = 0; index < (n - 1); index++)
                {
                    /* Send a message via UART periodically */
                    XMC_UART_CH_Transmit(CYBSP_DEBUG_UART_HW, data[index]);
                }

        memset(data,0,sizeof(data));
        
    }
}

/*******************************************************************************
* Function Name: main
********************************************************************************
* Summary:
* This is the main function. This function performs the following tasks:
*  1. Initial setup of device.
*  2. Starts the UART peripheral
*  3. Enables the system timer
*  4. Start the temperature measurement
*
* Parameters:
*  none
*
* Return:
*  int
*
*******************************************************************************/

int main(void)
{
    cy_rslt_t result;

    /* Initialize the device and board peripherals */
    result = cybsp_init();
    if (result != CY_RSLT_SUCCESS)
    {
        CY_ASSERT(0);
    }

    /* Start the UART peripheral */
    XMC_UART_CH_Start(CYBSP_DEBUG_UART_HW);

    /* Enable system timer */
    SysTick_Config(SystemCoreClock / TICKS_PER_SECOND);

    /* Start the temperature measurement */
    XMC_SCU_StartTempMeasurement();

    /* Placeholder for user application code. The while loop below can be replaced with user application code. */
    while(1U);
}

/* [] END OF FILE */
